# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20110112153317) do

  create_table "audiograms", :force => true do |t|
    t.integer  "patient_id"
    t.datetime "examdate"
    t.string   "comment"
    t.string   "image_location"
    t.float    "ac_rt_125"
    t.float    "ac_rt_250"
    t.float    "ac_rt_500"
    t.float    "ac_rt_1k"
    t.float    "ac_rt_2k"
    t.float    "ac_rt_4k"
    t.float    "ac_rt_8k"
    t.float    "ac_lt_125"
    t.float    "ac_lt_250"
    t.float    "ac_lt_500"
    t.float    "ac_lt_1k"
    t.float    "ac_lt_2k"
    t.float    "ac_lt_4k"
    t.float    "ac_lt_8k"
    t.float    "bc_rt_250"
    t.float    "bc_rt_500"
    t.float    "bc_rt_1k"
    t.float    "bc_rt_2k"
    t.float    "bc_rt_4k"
    t.float    "bc_rt_8k"
    t.float    "bc_lt_250"
    t.float    "bc_lt_500"
    t.float    "bc_lt_1k"
    t.float    "bc_lt_2k"
    t.float    "bc_lt_4k"
    t.float    "bc_lt_8k"
    t.boolean  "ac_rt_125_scaleout"
    t.boolean  "ac_rt_250_scaleout"
    t.boolean  "ac_rt_500_scaleout"
    t.boolean  "ac_rt_1k_scaleout"
    t.boolean  "ac_rt_2k_scaleout"
    t.boolean  "ac_rt_4k_scaleout"
    t.boolean  "ac_rt_8k_scaleout"
    t.boolean  "ac_lt_125_scaleout"
    t.boolean  "ac_lt_250_scaleout"
    t.boolean  "ac_lt_500_scaleout"
    t.boolean  "ac_lt_1k_scaleout"
    t.boolean  "ac_lt_2k_scaleout"
    t.boolean  "ac_lt_4k_scaleout"
    t.boolean  "ac_lt_8k_scaleout"
    t.boolean  "bc_rt_250_scaleout"
    t.boolean  "bc_rt_500_scaleout"
    t.boolean  "bc_rt_1k_scaleout"
    t.boolean  "bc_rt_2k_scaleout"
    t.boolean  "bc_rt_4k_scaleout"
    t.boolean  "bc_rt_8k_scaleout"
    t.boolean  "bc_lt_250_scaleout"
    t.boolean  "bc_lt_500_scaleout"
    t.boolean  "bc_lt_1k_scaleout"
    t.boolean  "bc_lt_2k_scaleout"
    t.boolean  "bc_lt_4k_scaleout"
    t.boolean  "bc_lt_8k_scaleout"
    t.float    "mask_ac_rt_125"
    t.float    "mask_ac_rt_250"
    t.float    "mask_ac_rt_500"
    t.float    "mask_ac_rt_1k"
    t.float    "mask_ac_rt_2k"
    t.float    "mask_ac_rt_4k"
    t.float    "mask_ac_rt_8k"
    t.float    "mask_ac_lt_125"
    t.float    "mask_ac_lt_250"
    t.float    "mask_ac_lt_500"
    t.float    "mask_ac_lt_1k"
    t.float    "mask_ac_lt_2k"
    t.float    "mask_ac_lt_4k"
    t.float    "mask_ac_lt_8k"
    t.float    "mask_bc_rt_250"
    t.float    "mask_bc_rt_500"
    t.float    "mask_bc_rt_1k"
    t.float    "mask_bc_rt_2k"
    t.float    "mask_bc_rt_4k"
    t.float    "mask_bc_rt_8k"
    t.float    "mask_bc_lt_250"
    t.float    "mask_bc_lt_500"
    t.float    "mask_bc_lt_1k"
    t.float    "mask_bc_lt_2k"
    t.float    "mask_bc_lt_4k"
    t.float    "mask_bc_lt_8k"
    t.string   "mask_ac_rt_125_type"
    t.string   "mask_ac_rt_250_type"
    t.string   "mask_ac_rt_500_type"
    t.string   "mask_ac_rt_1k_type"
    t.string   "mask_ac_rt_2k_type"
    t.string   "mask_ac_rt_4k_type"
    t.string   "mask_ac_rt_8k_type"
    t.string   "mask_ac_lt_125_type"
    t.string   "mask_ac_lt_250_type"
    t.string   "mask_ac_lt_500_type"
    t.string   "mask_ac_lt_1k_type"
    t.string   "mask_ac_lt_2k_type"
    t.string   "mask_ac_lt_4k_type"
    t.string   "mask_ac_lt_8k_type"
    t.string   "mask_bc_rt_250_type"
    t.string   "mask_bc_rt_500_type"
    t.string   "mask_bc_rt_1k_type"
    t.string   "mask_bc_rt_2k_type"
    t.string   "mask_bc_rt_4k_type"
    t.string   "mask_bc_rt_8k_type"
    t.string   "mask_bc_lt_250_type"
    t.string   "mask_bc_lt_500_type"
    t.string   "mask_bc_lt_1k_type"
    t.string   "mask_bc_lt_2k_type"
    t.string   "mask_bc_lt_4k_type"
    t.string   "mask_bc_lt_8k_type"
    t.boolean  "manual_input"
    t.string   "audiometer"
    t.string   "hospital"
    t.integer  "examiner_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "examiners", :force => true do |t|
    t.string   "worker_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "patients", :force => true do |t|
    t.string   "hp_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
